# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FirstqtUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1048, 702)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(0, 50, 221, 341))
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(-10, 390, 231, 291))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMidLineWidth(1)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setAutoScrollMargin(10)
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setRowCount(13)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(69)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget.verticalHeader().setMinimumSectionSize(23)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(220, 50, 831, 631))
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Panel)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(370, 490, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(300, 80, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Num_edit = QtWidgets.QPlainTextEdit(self.page)
        self.Num_edit.setGeometry(QtCore.QRect(300, 130, 241, 31))
        self.Num_edit.setObjectName("Num_edit")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(340, 210, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.SMSText_edit = QtWidgets.QPlainTextEdit(self.page)
        self.SMSText_edit.setGeometry(QtCore.QRect(260, 270, 331, 181))
        self.SMSText_edit.setObjectName("SMSText_edit")
        self.label.raise_()
        self.Num_edit.raise_()
        self.label_2.raise_()
        self.SMSText_edit.raise_()
        self.pushButton.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(240, 40, 311, 19))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_5.setGeometry(QtCore.QRect(320, 400, 161, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        self.listWidget = QtWidgets.QListWidget(self.page_2)
        self.listWidget.setGeometry(QtCore.QRect(260, 90, 256, 192))
        self.listWidget.setObjectName("listWidget")
        self.Actualizar = QtWidgets.QPushButton(self.page_2)
        self.Actualizar.setGeometry(QtCore.QRect(330, 550, 141, 41))
        self.Actualizar.setObjectName("Actualizar")
        self.progressBar = QtWidgets.QProgressBar(self.page_2)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(300, 330, 201, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.dateEdit = QtWidgets.QDateEdit(self.page_3)
        self.dateEdit.setGeometry(QtCore.QRect(140, 170, 141, 31))
        self.dateEdit.setObjectName("dateEdit")
        self.label_4 = QtWidgets.QLabel(self.page_3)
        self.label_4.setGeometry(QtCore.QRect(160, 30, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.timeEdit = QtWidgets.QTimeEdit(self.page_3)
        self.timeEdit.setGeometry(QtCore.QRect(310, 170, 131, 31))
        self.timeEdit.setObjectName("timeEdit")
        self.comboBox_2 = QtWidgets.QComboBox(self.page_3)
        self.comboBox_2.setGeometry(QtCore.QRect(490, 170, 101, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_5 = QtWidgets.QLabel(self.page_3)
        self.label_5.setGeometry(QtCore.QRect(140, 140, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(310, 140, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page_3)
        self.label_7.setGeometry(QtCore.QRect(490, 140, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page_3)
        self.label_8.setGeometry(QtCore.QRect(160, 260, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.page_3)
        self.label_9.setGeometry(QtCore.QRect(160, 340, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.page_3)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(270, 280, 151, 31))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.page_3)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(270, 360, 341, 161))
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_6.setGeometry(QtCore.QRect(390, 540, 111, 51))
        self.pushButton_6.setObjectName("pushButton_6")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.page_4)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 0, 831, 641))
        self.tableWidget_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget_3.setAutoFillBackground(True)
        self.tableWidget_3.setAutoScroll(True)
        self.tableWidget_3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_3.setShowGrid(True)
        self.tableWidget_3.setWordWrap(True)
        self.tableWidget_3.setCornerButtonEnabled(True)
        self.tableWidget_3.setRowCount(500)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 0, item)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(163)
        self.tableWidget_3.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget_3.verticalHeader().setVisible(False)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.page_5)
        self.tableWidget_2.setEnabled(True)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 0, 831, 631))
        self.tableWidget_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableWidget_2.setRowCount(500)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Numero")
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(268)
        self.stackedWidget.addWidget(self.page_5)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.page_8)
        self.tableWidget_4.setGeometry(QtCore.QRect(0, 0, 831, 541))
        self.tableWidget_4.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_4.setRowCount(500)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(1, 0, item)
        self.tableWidget_4.horizontalHeader().setDefaultSectionSize(276)
        self.tableWidget_4.verticalHeader().setVisible(False)
        self.Enviar = QtWidgets.QPushButton(self.page_8)
        self.Enviar.setGeometry(QtCore.QRect(350, 560, 131, 41))
        self.Enviar.setObjectName("Enviar")
        self.Actualiza_db = QtWidgets.QPushButton(self.page_8)
        self.Actualiza_db.setGeometry(QtCore.QRect(20, 570, 81, 31))
        self.Actualiza_db.setObjectName("Actualiza_db")
        self.progressBar_2 = QtWidgets.QProgressBar(self.page_8)
        self.progressBar_2.setGeometry(QtCore.QRect(610, 570, 118, 23))
        self.progressBar_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_2.setAutoFillBackground(False)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_2.setTextVisible(True)
        self.progressBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_2.setInvertedAppearance(False)
        self.progressBar_2.setObjectName("progressBar_2")
        self.stackedWidget.addWidget(self.page_8)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.Create_DB = QtWidgets.QPushButton(self.page_6)
        self.Create_DB.setGeometry(QtCore.QRect(560, 220, 81, 31))
        self.Create_DB.setObjectName("Create_DB")
        self.Name_create_db = QtWidgets.QPlainTextEdit(self.page_6)
        self.Name_create_db.setGeometry(QtCore.QRect(320, 220, 211, 31))
        self.Name_create_db.setObjectName("Name_create_db")
        self.label_10 = QtWidgets.QLabel(self.page_6)
        self.label_10.setGeometry(QtCore.QRect(120, 220, 171, 16))
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.page_6)
        self.IniciarBTN = QtWidgets.QPushButton(self.centralwidget)
        self.IniciarBTN.setGeometry(QtCore.QRect(10, 10, 121, 31))
        self.IniciarBTN.setObjectName("IniciarBTN")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(160, 10, 121, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.PuertosBTN = QtWidgets.QPushButton(self.centralwidget)
        self.PuertosBTN.setGeometry(QtCore.QRect(310, 10, 121, 31))
        self.PuertosBTN.setObjectName("PuertosBTN")
        self.ExitBTN = QtWidgets.QPushButton(self.centralwidget)
        self.ExitBTN.setGeometry(QtCore.QRect(930, 10, 101, 31))
        self.ExitBTN.setObjectName("ExitBTN")
        self.Connect_DB = QtWidgets.QPushButton(self.centralwidget)
        self.Connect_DB.setGeometry(QtCore.QRect(460, 10, 141, 31))
        self.Connect_DB.setObjectName("Connect_DB")
        self.crear_campaa = QtWidgets.QPushButton(self.centralwidget)
        self.crear_campaa.setGeometry(QtCore.QRect(630, 10, 121, 31))
        self.crear_campaa.setObjectName("crear_campaa")
        self.comboBox.raise_()
        self.treeWidget.raise_()
        self.tableWidget.raise_()
        self.stackedWidget.raise_()
        self.IniciarBTN.raise_()
        self.PuertosBTN.raise_()
        self.ExitBTN.raise_()
        self.Connect_DB.raise_()
        self.crear_campaa.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1048, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuHerramientas = QtWidgets.QMenu(self.menubar)
        self.menuHerramientas.setObjectName("menuHerramientas")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        MainWindow.setMenuBar(self.menubar)
        self.actionConectarModem = QtWidgets.QAction(MainWindow)
        self.actionConectarModem.setObjectName("actionConectarModem")
        self.actionEnviar_mensaje = QtWidgets.QAction(MainWindow)
        self.actionEnviar_mensaje.setObjectName("actionEnviar_mensaje")
        self.actionProgramar_mensaje = QtWidgets.QAction(MainWindow)
        self.actionProgramar_mensaje.setObjectName("actionProgramar_mensaje")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionIniciar = QtWidgets.QAction(MainWindow)
        self.actionIniciar.setObjectName("actionIniciar")
        self.actionPuertos = QtWidgets.QAction(MainWindow)
        self.actionPuertos.setObjectName("actionPuertos")
        self.menuArchivo.addAction(self.actionConectarModem)
        self.menuArchivo.addAction(self.actionEnviar_mensaje)
        self.menuArchivo.addAction(self.actionProgramar_mensaje)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionExit)
        self.menuHerramientas.addAction(self.actionIniciar)
        self.menuHerramientas.addAction(self.actionPuertos)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuHerramientas.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Menu"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Enviados"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "Recibidos"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "Programados"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "Base de datos"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No."))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Puerto"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Estado"))
        self.pushButton.setText(_translate("MainWindow", "Enviar"))
        self.label.setText(_translate("MainWindow", "Ingrese el Numero destinatario"))
        self.label_2.setText(_translate("MainWindow", "Escriba el mesnaje"))
        self.label_3.setText(_translate("MainWindow", "Selecciona Uno de los puertos disponibles:"))
        self.pushButton_5.setText(_translate("MainWindow", "Conectar"))
        self.Actualizar.setText(_translate("MainWindow", "Actualizar Puertos"))
        self.label_4.setText(_translate("MainWindow", "Selecciona el día y la hora para el envio del mensaje:"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Puerto"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "COM1"))
        self.label_5.setText(_translate("MainWindow", "Fecha:"))
        self.label_6.setText(_translate("MainWindow", "Hora:"))
        self.label_7.setText(_translate("MainWindow", "Puerto:"))
        self.label_8.setText(_translate("MainWindow", "Destinatario:"))
        self.label_9.setText(_translate("MainWindow", "Mensaje:"))
        self.pushButton_6.setText(_translate("MainWindow", "Prgramar"))
        self.tableWidget_3.setSortingEnabled(False)
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Numero"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mensaje"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Puerto"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Hora de envio"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mensaje"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Hore de recibido"))
        item = self.tableWidget_4.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Numero"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mensaje"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Enviado"))
        __sortingEnabled = self.tableWidget_4.isSortingEnabled()
        self.tableWidget_4.setSortingEnabled(False)
        self.tableWidget_4.setSortingEnabled(__sortingEnabled)
        self.Enviar.setText(_translate("MainWindow", "Enviar"))
        self.Actualiza_db.setText(_translate("MainWindow", "Actualiza"))
        self.Create_DB.setText(_translate("MainWindow", "Crear"))
        self.label_10.setText(_translate("MainWindow", "Introduce el nombre de la capaña:"))
        self.IniciarBTN.setText(_translate("MainWindow", "Iniciar"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Componer"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Programado"))
        self.PuertosBTN.setText(_translate("MainWindow", "Puertos"))
        self.ExitBTN.setText(_translate("MainWindow", "Salir"))
        self.Connect_DB.setText(_translate("MainWindow", "Conectar campaña"))
        self.crear_campaa.setText(_translate("MainWindow", "Crear campaña"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuHerramientas.setTitle(_translate("MainWindow", "Herramientas"))
        self.menuAyuda.setTitle(_translate("MainWindow", "Ayuda"))
        self.actionConectarModem.setText(_translate("MainWindow", "Conectar"))
        self.actionEnviar_mensaje.setText(_translate("MainWindow", "Enviar mensaje"))
        self.actionProgramar_mensaje.setText(_translate("MainWindow", "Programar mensaje"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionIniciar.setText(_translate("MainWindow", "Iniciar"))
        self.actionPuertos.setText(_translate("MainWindow", "Puertos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

